#!/usr/bin/env bash
[[ -z "${1}" ]] && {
printf '%s\n' "Error: Type the name of the py2 package you want to add." >&2
exit 1
}

echo """
[python2-${1}]
url = https://pypi.python.org/pypi/${1}/
regex = ([0-9\.]*)\.tar\.gz
""" >> archversion.conf
