#!/usr/bin/env bash

[[ -n "$1" ]] || {
    printf '%s\n' 'Error: Type the name of the py2 package you want to add.' >&2
    printf '%s\n' 'Example: ./addpy2 instagram (adds python2-instagram)' >&2
    exit 1
}

printf '\n%s\n%s\n%s\n\n' \
    "[python2-$1]" \
    "url = https://pypi.python.org/pypi/$1/" \
    'regex = ([0-9\.]*)\.tar\.gz' \
        >> archversion.conf
